"""empty message

Revision ID: f8f1fa6a445a
Revises: 51dbf980c923
Create Date: 2022-07-12 11:57:42.645477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f1fa6a445a'
down_revision = '51dbf980c923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
