version: '3'
networks:
  flaskblog_net:
    external: true
services:
  flaskblog:
    image: 'flaskblog:v1.0'
    restart: always
    container_name: flaskblog
    networks:
      flaskblog_net:
        ipv4_address: 172.32.0.3
    ports:
      - "80:80"
    depends_on:
      - mysql